/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StrategiesIndexRouteImport } from './routes/strategies/index'
import { Route as StrategiesNewRouteImport } from './routes/strategies/new'

const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesNewRoute = StrategiesNewRouteImport.update({
  id: '/strategies/new',
  path: '/strategies/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/predictions': typeof PredictionsRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/strategies': typeof StrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/predictions': typeof PredictionsRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/strategies': typeof StrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/predictions': typeof PredictionsRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/strategies/': typeof StrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/predictions' | '/strategies/new' | '/strategies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/predictions' | '/strategies/new' | '/strategies'
  id: '__root__' | '/' | '/predictions' | '/strategies/new' | '/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PredictionsRoute: typeof PredictionsRoute
  StrategiesNewRoute: typeof StrategiesNewRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/new': {
      id: '/strategies/new'
      path: '/strategies/new'
      fullPath: '/strategies/new'
      preLoaderRoute: typeof StrategiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PredictionsRoute: PredictionsRoute,
  StrategiesNewRoute: StrategiesNewRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
