import { appConfig } from "../../config.js";
import type { Frequency } from "../../gen/stockpicker/v1/strategy_pb.js";
import type { N8nWorkflow } from "../n8nTypes.js";
import { frequencyToCron, frequencyToName, getCurrentApiUrl } from "./n8nHelpers.js";

/**
 * Create a workflow template for a strategy that focuses on AI-powered stock analysis
 * Flow: Get Prepared Data -> AI Agent(s) Analysis -> Top 10 Stocks -> Standardized .md/.json -> Workflow Run
 */
export function createStrategyWorkflowTemplate(
  strategyId: string,
  strategyName: string,
  frequency: Frequency
): N8nWorkflow {
  const cronExpression = frequencyToCron(frequency);
  const frequencyName = frequencyToName(frequency);
  const apiUrl = getCurrentApiUrl();

  // Note: 'active' field is read-only in the API and cannot be set during creation
  // Workflow will be created as inactive by default, then activated separately when strategy starts
  const workflow: N8nWorkflow = {
    name: `Strategy: ${strategyName} (${frequencyName})`,
    nodes: [
      // Manual Trigger (for manual execution via UI button)
      {
        parameters: {},
        id: "manual-trigger",
        name: "Manual Trigger",
        type: "n8n-nodes-base.manualTrigger",
        typeVersion: 1.0,
        position: [250, 200],
      },
      // Webhook Trigger (for programmatic execution via API)
      // n8n will generate a unique webhookId when the workflow is saved
      {
        parameters: {
          httpMethod: "POST",
          path: "", // Empty path - n8n will generate webhookId automatically
          responseMode: "onReceived",
          options: {
            responseData: "success",
            responseCode: 200,
          },
        },
        id: "webhook-trigger",
        name: "Webhook Trigger",
        type: "n8n-nodes-base.webhook",
        typeVersion: 2.1,
        // webhookId will be auto-generated by n8n when workflow is saved
        position: [250, 100],
      },
      // Schedule Trigger (for cron-based execution) - managed by n8n
      {
        parameters: {
          triggerTimes: {
            item: [
              {
                mode: "cron",
                cronExpression: cronExpression,
              },
            ],
          },
        },
        id: "schedule-trigger",
        name: "Schedule Trigger",
        type: "n8n-nodes-base.scheduleTrigger",
        typeVersion: 1.2,
        position: [250, 300],
      },
      // Get Prepared Data from Apiserver - fetches sources, strategy, predictions, budget info
      {
        parameters: {
          url: `${apiUrl}/stockpicker.v1.StrategyService/PrepareDataForWorkflow`,
          method: "POST",
          sendHeaders: true,
          headerParameters: {
            parameters: [
              {
                name: "Content-Type",
                value: "application/json",
              },
              {
                name: "Connect-Protocol-Version",
                value: "1",
              },
            ],
          },
          sendBody: true,
          contentType: "json",
          specifyBody: "json",
          // Strategy ID is embedded directly in the workflow template (1-to-1 relationship)
          // Use jsonBody with n8n expression - matching format from n8n MCP examples
          // The expression creates a JavaScript object that n8n will stringify
          jsonBody: `={{ { id: "${strategyId}" } }}`,
          options: {
            response: {
              response: {
                neverError: true, // Don't throw errors, return response even on failure
                fullResponse: true, // Include status code and headers
                responseFormat: "json",
              },
            },
          },
          authentication: "genericCredentialType",
          genericAuthType: "httpHeaderAuth",
        },
        id: "get-prepared-data",
        name: "Get Prepared Data",
        type: "n8n-nodes-base.httpRequest",
        typeVersion: 4.2,
        position: [450, 300],
      },
      // Extract Input Data - parses apiserver response
      {
        parameters: {
          mode: "runOnceForAllItems",
          jsCode: `// Extract input data from ConnectRPC response
try {
  const inputData = $json;
  const response = inputData.json || inputData.body || {};

  const strategy = response.strategy || {};
  const activePredictions = response.activePredictions || response.active_predictions || [];
  const budget = response.budget || {};
  let sources = {};
  try {
    sources = typeof response.sources === 'string' ? JSON.parse(response.sources) : (response.sources || {});
  } catch (e) {
    console.error('Failed to parse sources:', e);
    sources = {};
  }

  return [{
    json: {
      strategy: strategy,
      activePredictions: activePredictions,
      budget: budget,
      sources: sources,
      strategyId: "${strategyId}"
    }
  }];
} catch (error) {
  // Throw error so it triggers error output
  throw new Error('Failed to extract input data: ' + (error instanceof Error ? error.message : String(error)));
}`,
        },
        id: "extract-input-data",
        name: "Extract Input Data",
        type: "n8n-nodes-base.code",
        typeVersion: 2,
        position: [650, 300],
      },
      // AI Agent 1 - using gpt-4o-mini
      {
        parameters: {
          url: "https://api.openai.com/v1/chat/completions",
          method: "POST",
          sendHeaders: true,
          headerParameters: {
            parameters: [
              {
                name: "Content-Type",
                value: "application/json",
              },
              {
                name: "Authorization",
                value: "={{ 'Bearer ' + $env.OPENAI_API_KEY }}",
              },
            ],
          },
          sendBody: true,
          bodyContentType: "json",
          jsonBody: `={{ JSON.stringify({
            "model": "gpt-4o-mini",
            "messages": [
              {
                "role": "system",
                "content": "You are a professional financial AI analyst specializing in technical analysis. Analyze stock data from multiple sources and provide your top 10 stock recommendations with detailed technical analysis, source tracing, and risk assessment. Your technical analysis should be based on available data sources (price data, volume, sentiment, etc.) and include actionable chart points."
              },
              {
                "role": "user",
                "content": "Analyze the following multi-source stock data and provide your top 10 stock recommendations with comprehensive technical analysis:\\n\\n" +
            "Strategy Parameters:\\n" +
            "- Strategy: " + $json.strategy.name + "\\n" +
            "- Time Horizon: " + $json.strategy.timeHorizon + "\\n" +
            "- Target Return: " + $json.strategy.targetReturnPct + "%\\n" +
            "- Risk Level: " + $json.strategy.riskLevel + "\\n" +
            "- Custom Instructions: " + ($json.strategy.customPrompt || "None") + "\\n\\n" +
            "Budget Information:\\n" +
            "- Monthly Budget: $" + ($json.budget.monthlyBudget || 0).toFixed(2) + "\\n" +
            "- Current Month Spent: $" + ($json.budget.currentMonthSpent || 0).toFixed(2) + "\\n" +
            "- Remaining Budget: $" + ($json.budget.remainingBudget || 0).toFixed(2) + "\\n" +
            "- Per Stock Allocation: $" + ($json.budget.perStockAllocation || 0).toFixed(2) + "\\n" +
            "- Available Investment Slots: " + ($json.budget.availableSlots || 0) + " stocks\\n" +
            "- Budget Utilization: " + ($json.budget.budgetUtilizationPct || 0).toFixed(1) + "%\\n" +
            "- Has Budget: " + ($json.budget.hasBudget ? "Yes" : "No") + "\\n" +
            "\\nIMPORTANT: Only recommend stocks if remaining budget >= per stock allocation. " +
            "Consider available_slots when selecting how many stocks to recommend. " +
            "If available_slots is limited, prioritize highest confidence/reward opportunities.\\n\\n" +
                  "Multi-Source Data:\\n" +
                  JSON.stringify($json.sources, null, 2) + "\\n\\n" +
                  "Active Predictions: " +
                  JSON.stringify($json.activePredictions, null, 2) + "\\n\\n" +
                  "Provide EXACTLY 10 stock recommendations in this JSON format:\\n" +
                  "{\\n" +
                  '  "top_stocks": [\\n' +
                  "    {\\n" +
                  '      "symbol": "AAPL",\\n' +
                  '      "entry_price": 150.00,\\n' +
                  '      "target_price": 165.00,\\n' +
                  '      "stop_loss_price": 142.50,\\n' +
                  '      "reasoning": "Detailed explanation...",\\n' +
                  '      "source_tracing": [\\n' +
                  "        {\\n" +
                  '          "source": "alpha_vantage",\\n' +
                  '          "contribution": "Top gainer with 5% increase",\\n' +
                  '          "data": {...}\\n' +
                  "        }\\n" +
                  "      ],\\n" +
                  '      "technical_analysis": {\\n' +
                  '        "trend": "bullish",\\n' +
                  '        "trend_strength": "strong",\\n' +
                  '        "support_level": 148.00,\\n' +
                  '        "resistance_level": 168.00,\\n' +
                  '        "current_price": 150.25,\\n' +
                  '        "price_change_pct": 2.5,\\n' +
                  '        "volume_analysis": "increasing",\\n' +
                  '        "volume_data": {\\n' +
                  '          "recent_volume": 1000000,\\n' +
                  '          "average_volume": 800000,\\n' +
                  '          "volume_trend": "above_average"\\n' +
                  '        },\\n' +
                  '        "price_levels": [\\n' +
                  '          {"level": 148.00, "type": "support", "strength": "strong"},\\n' +
                  '          {"level": 152.00, "type": "minor_resistance", "strength": "weak"},\\n' +
                  '          {"level": 168.00, "type": "resistance", "strength": "strong"}\\n' +
                  '        ],\\n' +
                  '        "indicators": {\\n' +
                  '          "rsi": 65.5,\\n' +
                  '          "rsi_signal": "neutral_to_bullish",\\n' +
                  '          "moving_average": {\\n' +
                  '            "sma_20": 148.50,\\n' +
                  '            "sma_50": 145.00,\\n' +
                  '            "position_vs_ma": "above_both"\\n' +
                  '          },\\n' +
                  '          "momentum": "positive"\\n' +
                  '        },\\n' +
                  '        "chart_pattern": "uptrend_continuation",\\n' +
                  '        "chart_points": [\\n' +
                  '          {"price": 148.00, "label": "Support", "type": "horizontal_line"},\\n' +
                  '          {"price": 152.00, "label": "Entry Zone", "type": "area"},\\n' +
                  '          {"price": 168.00, "label": "Target", "type": "horizontal_line"}\\n' +
                  '        ],\\n' +
                  '        "timeframe_analysis": {\\n' +
                  '          "short_term": "bullish",\\n' +
                  '          "medium_term": "bullish",\\n' +
                  '          "long_term": "neutral"\\n' +
                  '        },\\n' +
                  '        "data_sources_used": ["alpha_vantage", "reddit"],\\n' +
                  '        "analysis_notes": "Technical analysis based on price data from Alpha Vantage and sentiment from Reddit discussions"\\n' +
                  "      },\\n" +
                  '      "sentiment_score": 7.5,\\n' +
                  '      "overall_score": 8.2,\\n' +
                  '      "confidence_level": 0.75,\\n' +
                  '      "confidence_pct": 75,\\n' +
                  '      "risk_level": "medium",\\n' +
                  '      "risk_score": 5.5,\\n' +
                  '      "success_probability": 0.72,\\n' +
                  '      "hit_probability_pct": 72,\\n' +
                  '      "analysis": "Comprehensive analysis text...",\\n' +
                  '      "risk_assessment": "Medium risk with moderate confidence..."\\n' +
                  "    }\\n" +
                  "  ],\\n" +
                  '  "metadata": {\\n' +
                  '    "sources_used": ["alpha_vantage", "reddit", ...],\\n' +
                  '    "analysis_date": "' + new Date().toISOString() + '",\\n' +
                  '    "stocks_considered": 50\\n' +
                  "  }\\n" +
                  "}\\n\\n" +
                  "IMPORTANT TECHNICAL ANALYSIS REQUIREMENTS:\\n" +
                  "1. Base technical analysis on actual data from sources (price, volume, change percentages)\\n" +
                  "2. Calculate support/resistance levels from price data where available\\n" +
                  "3. Include chart_points array with specific price levels for chart generation\\n" +
                  "4. Extract volume analysis from source data (if available)\\n" +
                  "5. Calculate or estimate RSI, moving averages, momentum based on price movements\\n" +
                  "6. Identify chart patterns (uptrend, downtrend, consolidation, breakout, etc.)\\n" +
                  "7. Trace technical indicators back to source data in source_tracing\\n" +
                  "8. Ensure all price values are numbers, not strings\\n" +
                  "9. Technical analysis should be actionable for chart generation\\n\\n" +
                  "CONFIDENCE & RISK ASSESSMENT REQUIREMENTS:\\n" +
                  "1. confidence_level: decimal 0.0-1.0 representing confidence in recommendation (based on data quality, signal strength, source agreement)\\n" +
                  "2. confidence_pct: percentage 0-100 (same as confidence_level * 100)\\n" +
                  "3. risk_level: string - one of 'low', 'medium', 'high' based on volatility, stop loss distance, price stability\\n" +
                  "4. risk_score: number 1-10 where 1=very low risk, 10=very high risk\\n" +
                  "5. success_probability: decimal 0.0-1.0 representing probability of hitting target price based on technical analysis and signals\\n" +
                  "6. hit_probability_pct: percentage 0-100 (same as success_probability * 100)\\n" +
                  "7. Consider: data source agreement, signal strength, volume confirmation, price stability, stop loss distance\\n\\n" +
                  "Return ONLY valid JSON, no markdown formatting. Ensure all prices are numbers, not strings."
              }
            ],
            "temperature": 0.7,
            "response_format": {"type": "json_object"}
          }) }}`,
          options: {},
        },
        id: "ai-agent-1",
        name: "AI Agent 1 - gpt-4o-mini",
        type: "n8n-nodes-base.httpRequest",
        typeVersion: 4.2,
        position: [850, 200],
      },
      // AI Agent 2 - using gpt-4o
      {
        parameters: {
          url: "https://api.openai.com/v1/chat/completions",
          method: "POST",
          sendHeaders: true,
          headerParameters: {
            parameters: [
              {
                name: "Content-Type",
                value: "application/json",
              },
              {
                name: "Authorization",
                value: "={{ 'Bearer ' + $env.OPENAI_API_KEY }}",
              },
            ],
          },
          sendBody: true,
          bodyContentType: "json",
          jsonBody: `={{ JSON.stringify({
            "model": "gpt-4o",
            "messages": [
              {
                "role": "system",
                "content": "You are a professional financial AI analyst specializing in technical analysis. Analyze stock data from multiple sources and provide your top 10 stock recommendations with detailed technical analysis, source tracing, and risk assessment. Your technical analysis should be based on available data sources (price data, volume, sentiment, etc.) and include actionable chart points."
              },
              {
                "role": "user",
                "content": "Analyze the following multi-source stock data and provide your top 10 stock recommendations with comprehensive technical analysis:\\n\\n" +
            "Strategy Parameters:\\n" +
            "- Strategy: " + $json.strategy.name + "\\n" +
            "- Time Horizon: " + $json.strategy.timeHorizon + "\\n" +
            "- Target Return: " + $json.strategy.targetReturnPct + "%\\n" +
            "- Risk Level: " + $json.strategy.riskLevel + "\\n" +
            "- Custom Instructions: " + ($json.strategy.customPrompt || "None") + "\\n\\n" +
            "Budget Information:\\n" +
            "- Monthly Budget: $" + ($json.budget.monthlyBudget || 0).toFixed(2) + "\\n" +
            "- Current Month Spent: $" + ($json.budget.currentMonthSpent || 0).toFixed(2) + "\\n" +
            "- Remaining Budget: $" + ($json.budget.remainingBudget || 0).toFixed(2) + "\\n" +
            "- Per Stock Allocation: $" + ($json.budget.perStockAllocation || 0).toFixed(2) + "\\n" +
            "- Available Investment Slots: " + ($json.budget.availableSlots || 0) + " stocks\\n" +
            "- Budget Utilization: " + ($json.budget.budgetUtilizationPct || 0).toFixed(1) + "%\\n" +
            "- Has Budget: " + ($json.budget.hasBudget ? "Yes" : "No") + "\\n" +
            "\\nIMPORTANT: Only recommend stocks if remaining budget >= per stock allocation. " +
            "Consider available_slots when selecting how many stocks to recommend. " +
            "If available_slots is limited, prioritize highest confidence/reward opportunities.\\n\\n" +
                  "Multi-Source Data:\\n" +
                  JSON.stringify($json.sources, null, 2) + "\\n\\n" +
                  "Active Predictions: " +
                  JSON.stringify($json.activePredictions, null, 2) + "\\n\\n" +
                  "Provide EXACTLY 10 stock recommendations in this JSON format:\\n" +
                  "{\\n" +
                  '  "top_stocks": [\\n' +
                  "    {\\n" +
                  '      "symbol": "AAPL",\\n' +
                  '      "entry_price": 150.00,\\n' +
                  '      "target_price": 165.00,\\n' +
                  '      "stop_loss_price": 142.50,\\n' +
                  '      "reasoning": "Detailed explanation...",\\n' +
                  '      "source_tracing": [\\n' +
                  "        {\\n" +
                  '          "source": "alpha_vantage",\\n' +
                  '          "contribution": "Top gainer with 5% increase",\\n' +
                  '          "data": {...}\\n' +
                  "        }\\n" +
                  "      ],\\n" +
                  '      "technical_analysis": {\\n' +
                  '        "trend": "bullish",\\n' +
                  '        "trend_strength": "strong",\\n' +
                  '        "support_level": 148.00,\\n' +
                  '        "resistance_level": 168.00,\\n' +
                  '        "current_price": 150.25,\\n' +
                  '        "price_change_pct": 2.5,\\n' +
                  '        "volume_analysis": "increasing",\\n' +
                  '        "volume_data": {\\n' +
                  '          "recent_volume": 1000000,\\n' +
                  '          "average_volume": 800000,\\n' +
                  '          "volume_trend": "above_average"\\n' +
                  '        },\\n' +
                  '        "price_levels": [\\n' +
                  '          {"level": 148.00, "type": "support", "strength": "strong"},\\n' +
                  '          {"level": 152.00, "type": "minor_resistance", "strength": "weak"},\\n' +
                  '          {"level": 168.00, "type": "resistance", "strength": "strong"}\\n' +
                  '        ],\\n' +
                  '        "indicators": {\\n' +
                  '          "rsi": 65.5,\\n' +
                  '          "rsi_signal": "neutral_to_bullish",\\n' +
                  '          "moving_average": {\\n' +
                  '            "sma_20": 148.50,\\n' +
                  '            "sma_50": 145.00,\\n' +
                  '            "position_vs_ma": "above_both"\\n' +
                  '          },\\n' +
                  '          "momentum": "positive"\\n' +
                  '        },\\n' +
                  '        "chart_pattern": "uptrend_continuation",\\n' +
                  '        "chart_points": [\\n' +
                  '          {"price": 148.00, "label": "Support", "type": "horizontal_line"},\\n' +
                  '          {"price": 152.00, "label": "Entry Zone", "type": "area"},\\n' +
                  '          {"price": 168.00, "label": "Target", "type": "horizontal_line"}\\n' +
                  '        ],\\n' +
                  '        "timeframe_analysis": {\\n' +
                  '          "short_term": "bullish",\\n' +
                  '          "medium_term": "bullish",\\n' +
                  '          "long_term": "neutral"\\n' +
                  '        },\\n' +
                  '        "data_sources_used": ["alpha_vantage", "reddit"],\\n' +
                  '        "analysis_notes": "Technical analysis based on price data from Alpha Vantage and sentiment from Reddit discussions"\\n' +
                  "      },\\n" +
                  '      "sentiment_score": 7.5,\\n' +
                  '      "overall_score": 8.2,\\n' +
                  '      "confidence_level": 0.75,\\n' +
                  '      "confidence_pct": 75,\\n' +
                  '      "risk_level": "medium",\\n' +
                  '      "risk_score": 5.5,\\n' +
                  '      "success_probability": 0.72,\\n' +
                  '      "hit_probability_pct": 72,\\n' +
                  '      "analysis": "Comprehensive analysis text...",\\n' +
                  '      "risk_assessment": "Medium risk with moderate confidence..."\\n' +
                  "    }\\n" +
                  "  ],\\n" +
                  '  "metadata": {\\n' +
                  '    "sources_used": ["alpha_vantage", "reddit", ...],\\n' +
                  '    "analysis_date": "' + new Date().toISOString() + '",\\n' +
                  '    "stocks_considered": 50\\n' +
                  "  }\\n" +
                  "}\\n\\n" +
                  "IMPORTANT TECHNICAL ANALYSIS REQUIREMENTS:\\n" +
                  "1. Base technical analysis on actual data from sources (price, volume, change percentages)\\n" +
                  "2. Calculate support/resistance levels from price data where available\\n" +
                  "3. Include chart_points array with specific price levels for chart generation\\n" +
                  "4. Extract volume analysis from source data (if available)\\n" +
                  "5. Calculate or estimate RSI, moving averages, momentum based on price movements\\n" +
                  "6. Identify chart patterns (uptrend, downtrend, consolidation, breakout, etc.)\\n" +
                  "7. Trace technical indicators back to source data in source_tracing\\n" +
                  "8. Ensure all price values are numbers, not strings\\n" +
                  "9. Technical analysis should be actionable for chart generation\\n\\n" +
                  "CONFIDENCE & RISK ASSESSMENT REQUIREMENTS:\\n" +
                  "1. confidence_level: decimal 0.0-1.0 representing confidence in recommendation (based on data quality, signal strength, source agreement)\\n" +
                  "2. confidence_pct: percentage 0-100 (same as confidence_level * 100)\\n" +
                  "3. risk_level: string - one of 'low', 'medium', 'high' based on volatility, stop loss distance, price stability\\n" +
                  "4. risk_score: number 1-10 where 1=very low risk, 10=very high risk\\n" +
                  "5. success_probability: decimal 0.0-1.0 representing probability of hitting target price based on technical analysis and signals\\n" +
                  "6. hit_probability_pct: percentage 0-100 (same as success_probability * 100)\\n" +
                  "7. Consider: data source agreement, signal strength, volume confirmation, price stability, stop loss distance\\n\\n" +
                  "Return ONLY valid JSON, no markdown formatting. Ensure all prices are numbers, not strings."
              }
            ],
            "temperature": 0.7,
            "response_format": {"type": "json_object"}
          }) }}`,
          options: {},
        },
        id: "ai-agent-2",
        name: "AI Agent 2 - gpt-4o",
        type: "n8n-nodes-base.httpRequest",
        typeVersion: 4.2,
        position: [850, 300],
      },
      // AI Agent 3 - using gpt-4o-mini (different instance for variety)
      {
        parameters: {
          url: "https://api.openai.com/v1/chat/completions",
          method: "POST",
          sendHeaders: true,
          headerParameters: {
            parameters: [
              {
                name: "Content-Type",
                value: "application/json",
              },
              {
                name: "Authorization",
                value: "={{ 'Bearer ' + $env.OPENAI_API_KEY }}",
              },
            ],
          },
          sendBody: true,
          bodyContentType: "json",
          jsonBody: `={{ JSON.stringify({
            "model": "gpt-4o-mini",
            "messages": [
              {
                "role": "system",
                "content": "You are a professional financial AI analyst specializing in technical analysis. Analyze stock data from multiple sources and provide your top 10 stock recommendations with detailed technical analysis, source tracing, and risk assessment. Your technical analysis should be based on available data sources (price data, volume, sentiment, etc.) and include actionable chart points."
              },
              {
                "role": "user",
                "content": "Analyze the following multi-source stock data and provide your top 10 stock recommendations with comprehensive technical analysis:\\n\\n" +
            "Strategy Parameters:\\n" +
            "- Strategy: " + $json.strategy.name + "\\n" +
            "- Time Horizon: " + $json.strategy.timeHorizon + "\\n" +
            "- Target Return: " + $json.strategy.targetReturnPct + "%\\n" +
            "- Risk Level: " + $json.strategy.riskLevel + "\\n" +
            "- Custom Instructions: " + ($json.strategy.customPrompt || "None") + "\\n\\n" +
            "Budget Information:\\n" +
            "- Monthly Budget: $" + ($json.budget.monthlyBudget || 0).toFixed(2) + "\\n" +
            "- Current Month Spent: $" + ($json.budget.currentMonthSpent || 0).toFixed(2) + "\\n" +
            "- Remaining Budget: $" + ($json.budget.remainingBudget || 0).toFixed(2) + "\\n" +
            "- Per Stock Allocation: $" + ($json.budget.perStockAllocation || 0).toFixed(2) + "\\n" +
            "- Available Investment Slots: " + ($json.budget.availableSlots || 0) + " stocks\\n" +
            "- Budget Utilization: " + ($json.budget.budgetUtilizationPct || 0).toFixed(1) + "%\\n" +
            "- Has Budget: " + ($json.budget.hasBudget ? "Yes" : "No") + "\\n" +
            "\\nIMPORTANT: Only recommend stocks if remaining budget >= per stock allocation. " +
            "Consider available_slots when selecting how many stocks to recommend. " +
            "If available_slots is limited, prioritize highest confidence/reward opportunities.\\n\\n" +
                  "Multi-Source Data:\\n" +
                  JSON.stringify($json.sources, null, 2) + "\\n\\n" +
                  "Active Predictions: " +
                  JSON.stringify($json.activePredictions, null, 2) + "\\n\\n" +
                  "Provide EXACTLY 10 stock recommendations in this JSON format:\\n" +
                  "{\\n" +
                  '  "top_stocks": [\\n' +
                  "    {\\n" +
                  '      "symbol": "AAPL",\\n' +
                  '      "entry_price": 150.00,\\n' +
                  '      "target_price": 165.00,\\n' +
                  '      "stop_loss_price": 142.50,\\n' +
                  '      "reasoning": "Detailed explanation...",\\n' +
                  '      "source_tracing": [\\n' +
                  "        {\\n" +
                  '          "source": "alpha_vantage",\\n' +
                  '          "contribution": "Top gainer with 5% increase",\\n' +
                  '          "data": {...}\\n' +
                  "        }\\n" +
                  "      ],\\n" +
                  '      "technical_analysis": {\\n' +
                  '        "trend": "bullish",\\n' +
                  '        "trend_strength": "strong",\\n' +
                  '        "support_level": 148.00,\\n' +
                  '        "resistance_level": 168.00,\\n' +
                  '        "current_price": 150.25,\\n' +
                  '        "price_change_pct": 2.5,\\n' +
                  '        "volume_analysis": "increasing",\\n' +
                  '        "volume_data": {\\n' +
                  '          "recent_volume": 1000000,\\n' +
                  '          "average_volume": 800000,\\n' +
                  '          "volume_trend": "above_average"\\n' +
                  '        },\\n' +
                  '        "price_levels": [\\n' +
                  '          {"level": 148.00, "type": "support", "strength": "strong"},\\n' +
                  '          {"level": 152.00, "type": "minor_resistance", "strength": "weak"},\\n' +
                  '          {"level": 168.00, "type": "resistance", "strength": "strong"}\\n' +
                  '        ],\\n' +
                  '        "indicators": {\\n' +
                  '          "rsi": 65.5,\\n' +
                  '          "rsi_signal": "neutral_to_bullish",\\n' +
                  '          "moving_average": {\\n' +
                  '            "sma_20": 148.50,\\n' +
                  '            "sma_50": 145.00,\\n' +
                  '            "position_vs_ma": "above_both"\\n' +
                  '          },\\n' +
                  '          "momentum": "positive"\\n' +
                  '        },\\n' +
                  '        "chart_pattern": "uptrend_continuation",\\n' +
                  '        "chart_points": [\\n' +
                  '          {"price": 148.00, "label": "Support", "type": "horizontal_line"},\\n' +
                  '          {"price": 152.00, "label": "Entry Zone", "type": "area"},\\n' +
                  '          {"price": 168.00, "label": "Target", "type": "horizontal_line"}\\n' +
                  '        ],\\n' +
                  '        "timeframe_analysis": {\\n' +
                  '          "short_term": "bullish",\\n' +
                  '          "medium_term": "bullish",\\n' +
                  '          "long_term": "neutral"\\n' +
                  '        },\\n' +
                  '        "data_sources_used": ["alpha_vantage", "reddit"],\\n' +
                  '        "analysis_notes": "Technical analysis based on price data from Alpha Vantage and sentiment from Reddit discussions"\\n' +
                  "      },\\n" +
                  '      "sentiment_score": 7.5,\\n' +
                  '      "overall_score": 8.2,\\n' +
                  '      "confidence_level": 0.75,\\n' +
                  '      "confidence_pct": 75,\\n' +
                  '      "risk_level": "medium",\\n' +
                  '      "risk_score": 5.5,\\n' +
                  '      "success_probability": 0.72,\\n' +
                  '      "hit_probability_pct": 72,\\n' +
                  '      "analysis": "Comprehensive analysis text...",\\n' +
                  '      "risk_assessment": "Medium risk with moderate confidence..."\\n' +
                  "    }\\n" +
                  "  ],\\n" +
                  '  "metadata": {\\n' +
                  '    "sources_used": ["alpha_vantage", "reddit", ...],\\n' +
                  '    "analysis_date": "' + new Date().toISOString() + '",\\n' +
                  '    "stocks_considered": 50\\n' +
                  "  }\\n" +
                  "}\\n\\n" +
                  "IMPORTANT TECHNICAL ANALYSIS REQUIREMENTS:\\n" +
                  "1. Base technical analysis on actual data from sources (price, volume, change percentages)\\n" +
                  "2. Calculate support/resistance levels from price data where available\\n" +
                  "3. Include chart_points array with specific price levels for chart generation\\n" +
                  "4. Extract volume analysis from source data (if available)\\n" +
                  "5. Calculate or estimate RSI, moving averages, momentum based on price movements\\n" +
                  "6. Identify chart patterns (uptrend, downtrend, consolidation, breakout, etc.)\\n" +
                  "7. Trace technical indicators back to source data in source_tracing\\n" +
                  "8. Ensure all price values are numbers, not strings\\n" +
                  "9. Technical analysis should be actionable for chart generation\\n\\n" +
                  "CONFIDENCE & RISK ASSESSMENT REQUIREMENTS:\\n" +
                  "1. confidence_level: decimal 0.0-1.0 representing confidence in recommendation (based on data quality, signal strength, source agreement)\\n" +
                  "2. confidence_pct: percentage 0-100 (same as confidence_level * 100)\\n" +
                  "3. risk_level: string - one of 'low', 'medium', 'high' based on volatility, stop loss distance, price stability\\n" +
                  "4. risk_score: number 1-10 where 1=very low risk, 10=very high risk\\n" +
                  "5. success_probability: decimal 0.0-1.0 representing probability of hitting target price based on technical analysis and signals\\n" +
                  "6. hit_probability_pct: percentage 0-100 (same as success_probability * 100)\\n" +
                  "7. Consider: data source agreement, signal strength, volume confirmation, price stability, stop loss distance\\n\\n" +
                  "Return ONLY valid JSON, no markdown formatting. Ensure all prices are numbers, not strings."
              }
            ],
            "temperature": 0.8,
            "response_format": {"type": "json_object"}
          }) }}`,
          options: {},
        },
        id: "ai-agent-3",
        name: "AI Agent 3 - Risk Management",
        type: "n8n-nodes-base.httpRequest",
        typeVersion: 4.2,
        position: [850, 400],
      },
      // Merge AI Agent Results - combines successful responses from all 3 agents
      {
        parameters: {
          mode: "combine",
          combineBy: "combineAll",
          options: {},
        },
        id: "merge-ai-agent-results",
        name: "Merge AI Agent Results",
        type: "n8n-nodes-base.merge",
        typeVersion: 2.1,
        position: [1250, 300],
      },
      // Parse AI Analysis - extract top 10 stocks
      {
        parameters: {
          mode: "runOnceForAllItems",
          jsCode: `// Parse AI agent response and extract top 10 stocks
try {
  const response = $input.item.json;
  const body = response.body || response;
  const content = body.choices?.[0]?.message?.content || body.message?.content || '';

  if (!content) {
    throw new Error('AI agent returned empty response');
  }

  let aiAnalysis = null;
  try {
    aiAnalysis = JSON.parse(content);
  } catch (e) {
    throw new Error('Failed to parse AI analysis JSON: ' + (e instanceof Error ? e.message : String(e)));
  }

  const top10Stocks = (aiAnalysis.top_stocks || []).slice(0, 10);

  return [{
    json: {
      top10Stocks: top10Stocks,
      aiAnalysis: aiAnalysis,
      metadata: aiAnalysis.metadata || {},
      strategy: $node['Extract Input Data'].json.strategy,
      sources: $node['Extract Input Data'].json.sources,
      strategyId: "${strategyId}"
    }
  }];
} catch (error) {
  // Throw error so it triggers error output
  throw new Error('Failed to parse AI analysis: ' + (error instanceof Error ? error.message : String(error)));
}`,
        },
        id: "parse-ai-analysis",
        name: "Parse AI Analysis",
        type: "n8n-nodes-base.code",
        typeVersion: 2,
        position: [1250, 300],
      },
      // Generate JSON Output - standardized format
      {
        parameters: {
          mode: "runOnceForAllItems",
          jsCode: `// Generate standardized JSON output
const inputData = $json;
const top10 = inputData.top10Stocks || [];
const metadata = inputData.metadata || {};
const strategy = inputData.strategy || {};
const sources = inputData.sources || {};
const budget = inputData.budget || {};

// Standardized JSON output format
const jsonOutput = {
  format_version: "1.0",
  strategy_id: "${strategyId}",
  strategy_name: strategy.name || "",
  generated_at: new Date().toISOString(),
  recommendations: top10.map(stock => ({
    symbol: stock.symbol || "",
    entry_price: Number(stock.entry_price) || 0,
    target_price: Number(stock.target_price) || 0,
    stop_loss_price: Number(stock.stop_loss_price) || 0,
    reasoning: stock.reasoning || "",
    source_tracing: stock.source_tracing || [],
    technical_analysis: stock.technical_analysis || {},
    sentiment_score: Number(stock.sentiment_score) || 0,
    overall_score: Number(stock.overall_score) || 0,
    confidence_level: Number(stock.confidence_level) || 0,
    confidence_pct: Number(stock.confidence_pct) || 0,
    risk_level: stock.risk_level || "medium",
    risk_score: Number(stock.risk_score) || 5,
    success_probability: Number(stock.success_probability) || 0,
    hit_probability_pct: Number(stock.hit_probability_pct) || 0,
    analysis: stock.analysis || "",
    risk_assessment: stock.risk_assessment || ""
  })),
  metadata: {
    ...metadata,
    sources_analyzed: Object.keys(sources),
    recommendations_count: top10.length,
    budget: inputData.budget || {} // Include full budget data for reference
  }
};

return [{
  json: {
    json_output: JSON.stringify(jsonOutput),
    top10Stocks: top10,
    strategyId: "${strategyId}"
  }
}];`,
        },
        id: "generate-json-output",
        name: "Generate JSON Output",
        type: "n8n-nodes-base.code",
        typeVersion: 2,
        position: [1250, 200],
      },
      // Generate Markdown Output - standardized format that matches JSON
      {
        parameters: {
          mode: "runOnceForAllItems",
          jsCode: `// Generate standardized Markdown output that matches JSON recommendations
const inputData = $json;
const top10 = inputData.top10Stocks || [];
const strategy = inputData.strategy || {};
const sources = inputData.sources || {};

// Build markdown report that corresponds to JSON output
let markdown = '# Stock Analysis Report\\n\\n';
markdown += \`**Strategy:** \${strategy.name || 'N/A'}\\n\`;
markdown += \`**Time Horizon:** \${strategy.timeHorizon || 'N/A'}\\n\`;
markdown += \`**Target Return:** \${strategy.targetReturnPct || 0}%\\n\`;
markdown += \`**Risk Level:** \${strategy.riskLevel || 'N/A'}\\n\`;
markdown += \`**Generated:** \${new Date().toISOString()}\\n\\n\`;

markdown += '## Executive Summary\\n\\n';
markdown += \`This analysis identified \${top10.length} top stock recommendations based on multi-source data analysis.\\n\\n\`;

// Quick metrics summary for all recommendations
const avgConfidence = top10.length > 0
  ? top10.reduce((sum, s) => sum + (Number(s.confidence_pct) || Number(s.confidence_level) * 100 || 0), 0) / top10.length
  : 0;
const avgHitProb = top10.length > 0
  ? top10.reduce((sum, s) => sum + (Number(s.hit_probability_pct) || Number(s.success_probability) * 100 || 0), 0) / top10.length
  : 0;
const avgRiskScore = top10.length > 0
  ? top10.reduce((sum, s) => sum + (Number(s.risk_score) || 5), 0) / top10.length
  : 5;
const riskBreakdown = top10.reduce((acc, s) => {
  const risk = s.risk_level || "medium";
  acc[risk] = (acc[risk] || 0) + 1;
  return acc;
}, {});

markdown += '**Summary Metrics:**\\n';
markdown += \`- Average Confidence: \${avgConfidence.toFixed(0)}%\\n\`;
markdown += \`- Average Success Probability: \${avgHitProb.toFixed(0)}%\\n\`;
markdown += \`- Average Risk Score: \${avgRiskScore.toFixed(1)}/10\\n\`;
markdown += \`- Risk Breakdown: \${Object.entries(riskBreakdown).map(([level, count]) => \`\${level.toUpperCase()}: \${count}\`).join(', ') || 'N/A'}\\n\\n\`;

markdown += '## Top Stock Recommendations\\n\\n';

top10.forEach((stock, index) => {
  const symbol = stock.symbol || 'N/A';
  const entryPrice = Number(stock.entry_price) || 0;
  const targetPrice = Number(stock.target_price) || 0;
  const stopLossPrice = Number(stock.stop_loss_price) || 0;
  const overallScore = Number(stock.overall_score) || 0;

  // Confidence and risk metrics
  const confidencePct = Number(stock.confidence_pct) || (Number(stock.confidence_level) * 100) || 0;
  const hitProbPct = Number(stock.hit_probability_pct) || (Number(stock.success_probability) * 100) || 0;
  const riskLevel = stock.risk_level || "medium";
  const riskScore = Number(stock.risk_score) || 5;

  // Helper function to get confidence label
  function getConfidenceLabel(pct) {
    if (pct >= 80) return "Very High";
    if (pct >= 65) return "High";
    if (pct >= 50) return "Moderate";
    if (pct >= 35) return "Low";
    return "Very Low";
  }

  // Helper to get risk emoji/indicator
  function getRiskIndicator(level, score) {
    if (level === "low" || score <= 3) return "🟢";
    if (level === "medium" || score <= 6) return "🟡";
    return "🔴";
  }

  markdown += \`### \${index + 1}. \${symbol} \${getRiskIndicator(riskLevel, riskScore)}\\n\\n\`;

  // Quick glance metrics - prominently displayed
  markdown += '**Quick Metrics** *(Quick Glance)*:\\n';
  markdown += \`- 🎯 **Confidence:** \${confidencePct.toFixed(0)}% (\${getConfidenceLabel(confidencePct)})\\n\`;
  markdown += \`- ✅ **Success Probability:** \${hitProbPct.toFixed(0)}%\\n\`;
  markdown += \`- ⚠️ **Risk Level:** \${riskLevel.toUpperCase()} (Score: \${riskScore.toFixed(1)}/10)\\n\`;
  markdown += \`- ⭐ **Overall Score:** \${overallScore.toFixed(1)}/10\\n\\n\`;

  markdown += '**Price Points:**\\n';
  markdown += \`- Entry Price: $\${entryPrice.toFixed(2)}\\n\`;
  const targetReturnPct = ((targetPrice - entryPrice) / entryPrice) * 100;
  const stopLossPct = ((entryPrice - stopLossPrice) / entryPrice) * 100;
  markdown += \`- Target Price: $\${targetPrice.toFixed(2)} (+\${targetReturnPct.toFixed(2)}%)\\n\`;
  markdown += \`- Stop Loss: $\${stopLossPrice.toFixed(2)} (-\${stopLossPct.toFixed(2)}%)\\n\\n\`;

  if (stock.reasoning) {
    markdown += \`**Reasoning:** \${stock.reasoning}\\n\\n\`;
  }

  if (stock.analysis) {
    markdown += \`**Analysis:** \${stock.analysis}\\n\\n\`;
  }

  // Source tracing
  if (stock.source_tracing && stock.source_tracing.length > 0) {
    markdown += '**Sources:**\\n';
    stock.source_tracing.forEach(source => {
      markdown += \`- \${source.source}: \${source.contribution || 'See data'}\\n\`;
    });
    markdown += '\\n';
  }

  // Technical analysis - detailed and traceable
  if (stock.technical_analysis) {
    const ta = stock.technical_analysis;
    markdown += '**Technical Analysis:**\\n';

    if (ta.trend) {
      markdown += \`- Trend: \${ta.trend}\`;
      if (ta.trend_strength) {
        markdown += \` (\${ta.trend_strength})\`;
      }
      markdown += '\\n';
    }

    if (ta.current_price) {
      markdown += \`- Current Price: $\${ta.current_price.toFixed(2)}\`;
      if (ta.price_change_pct) {
        markdown += \` (\${ta.price_change_pct > 0 ? '+' : ''}\${ta.price_change_pct.toFixed(2)}%)\`;
      }
      markdown += '\\n';
    }

    // Price levels
    if (ta.price_levels && ta.price_levels.length > 0) {
      markdown += '- Price Levels:\\n';
      ta.price_levels.forEach(level => {
        markdown += \`  - $\${level.level.toFixed(2)}: \${level.type} (\${level.strength || 'N/A'})\\n\`;
      });
    } else {
      // Fallback to old format
      if (ta.support_level) {
        markdown += \`- Support Level: $\${ta.support_level}\\n\`;
      }
      if (ta.resistance_level) {
        markdown += \`- Resistance Level: $\${ta.resistance_level}\\n\`;
      }
    }

    // Volume analysis
    if (ta.volume_analysis) {
      markdown += \`- Volume: \${ta.volume_analysis}\\n\`;
      if (ta.volume_data) {
        const vd = ta.volume_data;
        if (vd.volume_trend) {
          markdown += \`  - Trend: \${vd.volume_trend}\\n\`;
        }
        if (vd.recent_volume && vd.average_volume) {
          const volRatio = (vd.recent_volume / vd.average_volume).toFixed(2);
          markdown += \`  - Recent vs Average: \${volRatio}x\\n\`;
        }
      }
    }

    // Technical indicators
    if (ta.indicators) {
      markdown += '- Indicators:\\n';
      if (ta.indicators.rsi !== undefined) {
        markdown += \`  - RSI: \${ta.indicators.rsi.toFixed(1)}\`;
        if (ta.indicators.rsi_signal) {
          markdown += \` (\${ta.indicators.rsi_signal})\`;
        }
        markdown += '\\n';
      }
      if (ta.indicators.moving_average) {
        const ma = ta.indicators.moving_average;
        markdown += \`  - Moving Averages:\\n\`;
        if (ma.sma_20) markdown += \`    - SMA 20: $\${ma.sma_20.toFixed(2)}\\n\`;
        if (ma.sma_50) markdown += \`    - SMA 50: $\${ma.sma_50.toFixed(2)}\\n\`;
        if (ma.position_vs_ma) markdown += \`    - Position: \${ma.position_vs_ma}\\n\`;
      }
      if (ta.indicators.momentum) {
        markdown += \`  - Momentum: \${ta.indicators.momentum}\\n\`;
      }
    }

    // Chart pattern
    if (ta.chart_pattern) {
      markdown += \`- Chart Pattern: \${ta.chart_pattern}\\n\`;
    }

    // Chart points for visualization
    if (ta.chart_points && ta.chart_points.length > 0) {
      markdown += '- Chart Points:\\n';
      ta.chart_points.forEach(point => {
        markdown += \`  - $\${point.price.toFixed(2)}: \${point.label} (\${point.type || 'point'})\\n\`;
      });
    }

    // Timeframe analysis
    if (ta.timeframe_analysis) {
      markdown += '- Timeframe Analysis:\\n';
      if (ta.timeframe_analysis.short_term) {
        markdown += \`  - Short-term: \${ta.timeframe_analysis.short_term}\\n\`;
      }
      if (ta.timeframe_analysis.medium_term) {
        markdown += \`  - Medium-term: \${ta.timeframe_analysis.medium_term}\\n\`;
      }
      if (ta.timeframe_analysis.long_term) {
        markdown += \`  - Long-term: \${ta.timeframe_analysis.long_term}\\n\`;
      }
    }

    // Data source tracing for technical analysis
    if (ta.data_sources_used && ta.data_sources_used.length > 0) {
      markdown += \`- Technical Analysis Sources: \${ta.data_sources_used.join(', ')}\\n\`;
    }

    if (ta.analysis_notes) {
      markdown += \`- Analysis Notes: \${ta.analysis_notes}\\n\`;
    }

    markdown += '\\n';
  }

  if (stock.risk_assessment) {
    markdown += \`**Risk Assessment:** \${stock.risk_assessment}\\n\\n\`;
  }

  markdown += '---\\n\\n';
});

markdown += '## Source Attribution\\n\\n';
markdown += \`This analysis used data from: \${Object.keys(sources).join(', ') || 'No sources available'}\\n\\n\`;

markdown += '## Methodology\\n\\n';
markdown += 'Stocks were analyzed using multi-source data aggregation, AI-powered analysis, and risk assessment based on strategy parameters.\\n';

return [{
  json: {
    markdown_output: markdown,
    strategyId: "${strategyId}"
  }
}];`,
        },
        id: "generate-markdown-output",
        name: "Generate Markdown Output",
        type: "n8n-nodes-base.code",
        typeVersion: 2,
        position: [1250, 400],
      },
      // Combine Outputs - ensure JSON and Markdown are consistent
      {
        parameters: {
          mode: "runOnceForAllItems",
          jsCode: `// Combine JSON and Markdown outputs, ensuring consistency
const jsonItem = $node['Generate JSON Output'].json || {};
const markdownItem = $node['Generate Markdown Output'].json || {};
const inputDataItem = $node['Extract Input Data'].json || {};
const aiAnalysisItem = $node['Parse AI Analysis'].json || {};

const jsonOutput = jsonItem.json_output || '{}';
const markdownOutput = markdownItem.markdown_output || '# Stock Analysis Report\\n\\nNo data available.';
// Capture input data (sources, strategy, activePredictions)
const inputData = JSON.stringify(inputDataItem);
// Capture raw AI analysis output
const aiAnalysis = JSON.stringify(aiAnalysisItem.aiAnalysis || aiAnalysisItem);

// Parse JSON to validate it matches markdown
let jsonObj = {};
try {
  jsonObj = JSON.parse(jsonOutput);
} catch (e) {
  console.error('Error parsing JSON output for validation:', e);
}

// Validate consistency: ensure markdown mentions all symbols from JSON
const jsonSymbols = (jsonObj.recommendations || []).map(r => r.symbol).filter(Boolean);
const markdownSymbols = markdownOutput.match(/### \\d+\\. ([A-Z]+)/g) || [];
const markdownSymbolsExtracted = markdownSymbols.map(m => m.replace(/### \\d+\\. /, ''));

// Check if all JSON symbols appear in markdown
const missingInMarkdown = jsonSymbols.filter(s => !markdownSymbolsExtracted.includes(s));
if (missingInMarkdown.length > 0) {
  console.warn('⚠️ Warning: Some JSON recommendations missing in markdown:', missingInMarkdown);
}

return [{
  json: {
    strategy_id: "${strategyId}",
    json_output: jsonOutput,
    markdown_output: markdownOutput,
    input_data: inputData,
    ai_analysis: aiAnalysis,
    timestamp: new Date().toISOString(),
    format_version: "1.0",
    validated: missingInMarkdown.length === 0
  }
}];`,
        },
        id: "combine-outputs",
        name: "Combine & Validate Outputs",
        type: "n8n-nodes-base.code",
        typeVersion: 2,
        position: [1450, 300],
      },
      // Complete Workflow Run - updates existing workflow run (created at start) with results and creates predictions
      // The workflow run was already created when "Get Prepared Data" was called at the start
      // This node updates it with the final outputs and creates predictions for top 3 stocks
      {
        parameters: {
          url: `${apiUrl}/stockpicker.v1.StrategyService/CreatePredictionsFromWorkflow`,
          method: "POST",
          sendHeaders: true,
          headerParameters: {
            parameters: [
              {
                name: "Content-Type",
                value: "application/json",
              },
              {
                name: "Connect-Protocol-Version",
                value: "1",
              },
            ],
          },
          sendBody: true,
          bodyContentType: "json",
          jsonBody:
            "={{ JSON.stringify({ strategyId: $json.strategy_id, jsonOutput: $json.json_output, markdownOutput: $json.markdown_output, executionId: $execution.id, inputData: $json.input_data, aiAnalysis: $json.ai_analysis }) }}",
          options: {},
          authentication: "genericCredentialType",
          genericAuthType: "httpHeaderAuth",
        },
        id: "complete-workflow-run",
        name: "Complete Workflow Run",
        type: "n8n-nodes-base.httpRequest",
        typeVersion: 4.2,
        position: [1650, 300],
      },
    ],
    connections: {
      "Manual Trigger": {
        main: [[{ node: "Get Prepared Data", type: "main", index: 0 }]],
      },
      "Webhook Trigger": {
        main: [[{ node: "Get Prepared Data", type: "main", index: 0 }]],
      },
      "Schedule Trigger": {
        main: [[{ node: "Get Prepared Data", type: "main", index: 0 }]],
      },
      "Get Prepared Data": {
        main: [[{ node: "Extract Input Data", type: "main", index: 0 }]],
      },
      "Extract Input Data": {
        main: [
          [
            { node: "AI Agent 1 - gpt-4o-mini", type: "main", index: 0 },
            { node: "AI Agent 2 - gpt-4o", type: "main", index: 0 },
            { node: "AI Agent 3 - gpt-4o-mini", type: "main", index: 0 },
          ],
        ],
      },
      "AI Agent 1 - gpt-4o-mini": {
        main: [[{ node: "Merge AI Agent Results", type: "main", index: 0 }]],
      },
      "AI Agent 2 - gpt-4o": {
        main: [[{ node: "Merge AI Agent Results", type: "main", index: 0 }]],
      },
      "AI Agent 3 - gpt-4o-mini": {
        main: [[{ node: "Merge AI Agent Results", type: "main", index: 0 }]],
      },
      "Merge AI Agent Results": {
        main: [[{ node: "Parse AI Analysis", type: "main", index: 0 }]],
      },
      "Parse AI Analysis": {
        main: [
          [
            { node: "Generate JSON Output", type: "main", index: 0 },
            { node: "Generate Markdown Output", type: "main", index: 0 },
          ],
        ],
      },
      "Generate JSON Output": {
        main: [[{ node: "Combine & Validate Outputs", type: "main", index: 0 }]],
      },
      "Generate Markdown Output": {
        main: [[{ node: "Combine & Validate Outputs", type: "main", index: 0 }]],
      },
      "Combine & Validate Outputs": {
        main: [[{ node: "Complete Workflow Run", type: "main", index: 0 }]],
      },
    },
    settings: {
      executionOrder: "v1",
      saveDataErrorExecution: "all",
      saveDataSuccessExecution: "none",
      saveManualExecutions: true,
      saveExecutionProgress: false,
    },
  };

  return workflow;
}
